name: Haskell CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        plan:
          - { resolver: "--resolver=lts-16.31" }
          - { resolver: "--resolver=lts-18.28" }
          - { resolver: "--resolver=lts-19.13" }
          - { resolver: "--resolver=nightly" }
        include:
          - os: ubuntu-latest
            apt-get: java-common

    runs-on: ${{ matrix.os }}

    steps:
    - name: Install ${{ matrix.os }} Packages
      uses: mstksg/get-package@2a4b48d55d72d43ca89ae58ec9ca1397d34a1c35
      with:
        apt-get: ${{ matrix.apt-get }}
        brew: ${{ matrix.brew }}
    - uses: actions/checkout@v2

    - name: Cache Stack on unix
      id: cache-stack-unix
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ matrix.os }}-${{ matrix.plan.build }}-stack-home-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
      if: contains(matrix.os, 'windows') == false

    - name: Cache Stack on windows
      id: cache-stack-windows
      uses: actions/cache@v1
      with:
        path: ~/AppData/Local/Programs/stack
        key: ${{ matrix.os }}-${{ matrix.plan.build }}-stack-home-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
      if: contains(matrix.os, 'windows')

    - name: Setup stack
      uses: haskell/actions/setup@v1
      with:
        enable-stack: true
        stack-no-global: true

    - name: Install dependencies on unix
      run: |
        set -ex
        stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies
        set +ex
      env:
        ARGS: ${{ matrix.plan.resolver }}
      if: contains(matrix.os, 'windows') == false

    - name: Install dependencies on windows
      shell: powershell
      run: |
        stack --no-terminal --install-ghc ${env:ARGS} test --bench --only-dependencies
      env:
        ARGS: ${{ matrix.plan.resolver }}
      if: contains(matrix.os, 'windows')

    - name: Build on unix
      run: |
        set -ex
        stack --no-terminal --install-ghc $ARGS test --coverage --bench --no-run-benchmarks --haddock --no-haddock-deps
        set +ex
      env:
        ARGS: ${{ matrix.plan.resolver }}
      if: contains(matrix.os, 'windows') == false

    - name: Build on windows
      shell: powershell
      run: |
        stack --no-terminal --install-ghc ${env:ARGS} test --coverage --bench --no-run-benchmarks --haddock --no-haddock-deps
      env:
        ARGS: ${{ matrix.plan.resolver }}
      if: contains(matrix.os, 'windows')
