---
name: HLint

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: "Set up HLint"
        uses: haskell-actions/hlint-setup@fe9cd1cd1af94a23900c06738e73f6ddb092966a
        with:
          version: latest

      - name: "Run HLint"
        uses: haskell-actions/hlint-run@eaca4cfbf4a69f4eb875df38b6bc3e1657020378
        with:
          path: '["src/", "test/"]'
          fail-on: suggestion
