name: HLint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 'Set up HLint'
      uses: haskell-actions/hlint-setup@v2
      with:
        version: '3.5'

    - name: 'Run HLint'
      uses: haskell-actions/hlint-run@v2
      with:
        path: '["src/", "test/"]'
        fail-on: suggestion
