---
name: Check Spelling

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
    types:
      - "opened"
      - "reopened"
      - "synchronize"
  issue_comment:
    types: [created]

permissions: {}

jobs:
  spelling:
    name: Check Spelling
    permissions:
      actions: read
      contents: read
      pull-requests: read
      security-events: write
    outputs:
      followup: ${{ steps.spelling.outputs.followup }}
    runs-on: ubuntu-latest
    if: >-
      ${{ contains(github.event_name, 'pull_request')
      || github.event_name == 'push' }}
    concurrency:
      group: spelling-${{ github.event.pull_request.number || github.ref }}
      # note: If you use only_check_changed_files,
      # you do not want cancel-in-progress
      cancel-in-progress: true
    steps:
      - name: check-spelling
        id: spelling
        uses: check-spelling/check-spelling@c635c2f3f714eec2fcf27b643a1919b9a811ef2e
        with:
          suppress_push_for_open_pull_request: |
            ${{ github.actor != 'dependabot[bot]' && 1 }}
          checkout: true
          check_file_names: 1
          spell_check_this: check-spelling/spell-check-this@v0.0.25
          post_comment: 0
          use_magic_file: 1
          report-timing: 1
          experimental_apply_changes_via_bot: 1
          extra_dictionaries: |
            cspell:aws/aws.txt
            cspell:haskell/dict/haskell.txt
            cspell:software-terms/dict/softwareTerms.txt
            cspell:filetypes/filetypes.txt

  comment-push:
    name: Report (Push)
    # If your workflow isn't running on push, you can remove this job
    runs-on: ubuntu-latest
    needs: spelling
    permissions:
      actions: read
      contents: write
    if: >
      (success() || failure())
      && needs.spelling.outputs.followup
      && github.event_name == 'push'
    steps:
      - name: comment
        uses: check-spelling/check-spelling@c635c2f3f714eec2fcf27b643a1919b9a811ef2e
        with:
          checkout: true
          spell_check_this: check-spelling/spell-check-this@v0.0.25
          task: ${{ needs.spelling.outputs.followup }}

  comment-pr:
    name: Report (PR)
    # If you workflow isn't running on pull_request*, you can remove this job
    runs-on: ubuntu-latest
    needs: spelling
    permissions:
      actions: read
      contents: read
      pull-requests: write
    if: >
      (success() || failure())
      && needs.spelling.outputs.followup
      && contains(github.event_name, 'pull_request')
    steps:
      - name: comment
        uses: check-spelling/check-spelling@c635c2f3f714eec2fcf27b643a1919b9a811ef2e
        with:
          checkout: true
          spell_check_this: check-spelling/spell-check-this@v0.0.25
          task: ${{ needs.spelling.outputs.followup }}
          experimental_apply_changes_via_bot: 1

  update:
    name: Update PR
    permissions:
      actions: read
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: >-
      ${{ github.event_name == 'issue_comment'
      && github.event.issue.pull_request
      && contains(github.event.comment.body, '@check-spelling-bot apply') }}
    concurrency:
      group: spelling-update-${{ github.event.issue.number }}
      cancel-in-progress: false
    steps:
      - name: apply spelling updates (trusted users)
        if: ${{ github.actor == 'marcellussiegburg' }}
        uses: check-spelling/check-spelling@c635c2f3f714eec2fcf27b643a1919b9a811ef2e
        with:
          experimental_apply_changes_via_bot: 1
          checkout: true
          ssh_key: "${{ secrets.CHECK_SPELLING }}"

      - name: apply spelling updates (fork-safe)
        if: ${{ github.actor != 'marcellussiegburg' }}
        uses: check-spelling/check-spelling@c635c2f3f714eec2fcf27b643a1919b9a811ef2e
        with:
          experimental_apply_changes_via_bot: 1
          checkout: true
          github_token: "${{ github.token }}"
